#!/bin/bash

query=($*)
[ -z $query ] && exit 1
list=$(torrentscrap "$(echo $query | sed 's/ /+/g')")
choice=$(echo "$list" | fzf --tac)
download=$(echo $choice | awk '{print $NF}')
! [ -z $download ] && aria2c -d ~/Downloads --seed-time=0 https://nyaa.si$download &
