#!/bin/sh 

colorscheme="$(ls ~/.config/colorschemes/ | dmenu -l 10)"
folder=~/.config/colorschemes/

rm $folder/current
cp $folder/$colorscheme $folder/current
xrdb ~/.Xresources

# nvim colors
echo "colorscheme $colorscheme" > ~/.config/nvim/color.vim
echo "g:airline_theme = $colorscheme" >> ~/.config/nvim/color.vim

# zathura colors
zathuracolors

# dunst colors 
killall dunst 
fg=$(colorsXresources dunst.foreground)
bg=$(colorsXresources dunst.background)
fr=$(colorsXresources dunst.frame)
dunst -config ~/.config/dunst/dunstrc -lb "$bg" -nb "$bg" -cb "$bg" -lf "$fg" -bf "fg" -cf "$fg" -nf "$fg" -frame_color "$fr" &
