#!/bin/sh

colorscheme=$(sed "1s/.*\///; s/\"//" ~/.Xresources  | head -n 1)
[ -z $1 ] && wall=$(nsxiv -qo $HOME/Wallpapers/*) || wall="$1"
$HOME/bin/convertWall.py "$colorscheme" "$wall" && feh --bg-scale $HOME/Wallpapers/wall.png
