#!/bin/sh

colorscheme=$(sed "1s/.*\///; s/\"//" ~/.Xresources  | head -n 1)
[ -z $1 ] && wall=$(nsxiv -qo ~/Wallpapers/*) || wall="$1"
/home/samy/Coding/scripts/convertWall.py "$colorscheme" "$wall" && feh --bg-scale ~/Wallpapers/wall.png
