#!/bin/sh

export XDG_RUNTIME_DIR=/run/user/$(id -u)

todo_path="$HOME/Notes/todo"
cal_path="$HOME/Notes/cal"

calendar-cli --config-section todo todo list --timestamp-format "%m-%d" > $todo_path

calendar-cli \
    --config-section calendar calendar agenda \
    --agenda-days 1 \
    --event-template '{dtstart} {location} {summary}' \
    --timestamp-format "%d %H:%M" |
    sed 's/\\n//g' | sed -r '/^\s*$/d' > $cal_path
