#!/bin/sh 

status=$(bluetoothctl info 14:3F:A6:B2:9F:BA | grep -i connected | cut -d " " -f 2)

if [ $status = "no" ]; then
    bluetoothctl power on &&
    bluetoothctl connect 14:3F:A6:B2:9F:BA
else
    bluetoothctl disconnect 14:3F:A6:B2:9F:BA
fi
