#!/bin/sh

address=14:3F:A6:B2:9F:BA

status=$(bluetoothctl info "$address" | grep -i connected | cut -d " " -f 2)

if [ $status = "no" ]; then
    bluetoothctl power on &&
    bluetoothctl connect "$address"
else
    bluetoothctl disconnect "$address"
fi
