#!/bin/sh

export DISPLAY=:0

acpi -b | awk -F'[,:%]' '{print $2, $3}' | {
	read -r status capacity

	if [ "$status" = Discharging -a "$capacity" -lt 20 ]; then
		/bin/notify-send "LOW BATTERY";
        /bin/mpv $HOME/.config/hangouts.mp3 --volume=60
	fi
}

exit 0
