#!/bin/sh 

echo 90 | sudo -A tee /sys/class/power_supply/BAT0/charge_stop_threshold
echo 85 | sudo -A tee /sys/class/power_supply/BAT0/charge_start_threshold
echo 90 | sudo -A tee /sys/class/power_supply/BAT0/charge_stop_threshold
echo 85 | sudo -A tee /sys/class/power_supply/BAT0/charge_start_threshold
