#!/bin/sh

choice=$(echo "sleep\nreboot\nshutdown" | dmenu -i -p choice) || exit 1

case "$choice" in
    "sleep")
        loginctl suspend
        ;;
    "reboot")
        loginctl reboot
        ;;
    "shutdown")
        loginctl poweroff
        ;;
esac
