#!/bin/sh

[ -z $1 ] && image=$(sxiv ~/Wallpapers -bot) || image=$1 
[ -z "$image" ] && exit 1
wal -i "$image" -ntq
cat ~/.cache/wal/colors | pywalconvert > ~/.config/colorschemes/xresources
feh --bg-scale "$image"
theme xresources
