#!/bin/sh

status=$(cat /sys/class/power_supply/BAT0/status)
capacity=$(cat /sys/class/power_supply/BAT0/capacity)

if [ "$status" != Discharging ]; then
    printf "^C2^ﮣ^d^ %d%%" "$capacity"
elif [ "$capacity" -ge 75 ]; then
    printf "^C2^  ^d^ %d%%" "$capacity"
elif [ "$capacity" -ge 50 -a "$capacity" -lt 75 ]; then
    printf "^C3^  ^d^ %d%%" "$capacity"
elif [ "$capacity" -ge 25 -a "$capacity" -lt 50 ]; then
    printf "^C3^  ^d^ %d%%" "$capacity"
else
    printf "^C1^  ^d^  %d%%" "$capacity"
fi
