#!/bin/sh

[ -z $1 ] && colorscheme="$(ls ~/.config/colorschemes/ | dmenu -i -l 10)" || colorscheme="$1"
[ -z $colorscheme ] && exit 1

sed -i "1s,.*,#include \"/home/samy/.config/colorschemes/$colorscheme\"," /home/samy/.Xresources
xrdb ~/.Xresources

# wallpaper
# convert -size 1920x1080 xc:"$(xrdb -query | grep "*.background" | awk '{print $NF}')" ~/Wallpapers/wall.png \
#     && feh --bg-scale ~/Wallpapers/wall.png
# convertWall.py "$colorscheme" "$wall" && feh --bg-scale ~/Wallpapers/wall.png

# nvim colors
vim_colorscheme="$colorscheme"
sed -i "s/local colorscheme .*/local colorscheme = \"$vim_colorscheme\"/" ~/.config/nvim/lua/user/colorscheme.lua

# dwm live reload
xdotool key super+shift+x

# zathura colors
zathuracolors

# dunst colors
killall dunst
fg=$(colorsXresources dunst.foreground)
bg=$(colorsXresources dunst.background)
fr=$(colorsXresources dunst.frame)
sed -i "s/frame_color .*/frame_color = \"$fr\"/" ~/.config/dunst/dunstrc
sed -i "s/foreground .*/foreground = \"$fg\"/g" ~/.config/dunst/dunstrc
sed -i "s/background .*/background = \"$bg\"/g" ~/.config/dunst/dunstrc

dunst &

# GTK
# oomox-cli /opt/oomox/scripted_colors/xresources/xresources-reverse
# sed "s/gtk-theme-name=.*/gtk-theme-name=oomox-xresources-reverse/" ~/.config/gtk-3.0/settings.ini -i
