#!/bin/sh 

# TODO move color.vim to init.vim

colorscheme="$(ls ~/.config/colorschemes/ | dmenu -i -l 10)"
light=$(echo $colorscheme | rev | cut -s -d- -f1 | rev)
[ -z $colorscheme ] && exit 1

sed -i "1s,.*,#include \"/home/samy/.config/colorschemes/$colorscheme\"," /home/samy/.Xresources
xrdb ~/.Xresources

# nvim colors
vim_colorscheme=$(echo $colorscheme | cut -d- -f1)
sed -i "s/colorscheme .*/colorscheme $vim_colorscheme/" ~/.config/nvim/init.vim
if [ "$light" = "light" ]
then 
    sed -i "s/set bg=.*/set bg=light/" ~/.config/nvim/init.vim 
else
    sed -i "s/set bg=.*/set bg=dark/" ~/.config/nvim/init.vim 
fi

# zathura colors
zathuracolors

# dunst colors 
killall dunst 
fg=$(colorsXresources dunst.foreground)
bg=$(colorsXresources dunst.background)
fr=$(colorsXresources dunst.frame)
dunst -config ~/.config/dunst/dunstrc -lb "$bg" -nb "$bg" -cb "$bg" -lf "$fg" -bf "fg" -cf "$fg" -nf "$fg" -frame_color "$fr" &

# wallpaper 
# convert -size 1920x1080 xc:"$(xrdb -query | grep "*.background" | awk '{print $NF}')" ~/Wallpapers/wall.png
# xwallpaper --zoom ~/Wallpapers/wall.png

# gtk
if [ "$light" = "light" ] 
then 
    sed -i "2s/.*/gtk-theme-name=Arc/" ~/.config/gtk-3.0/settings.ini
else
    sed -i "2s/.*/gtk-theme-name=Arc-Dark/" ~/.config/gtk-3.0/settings.ini
fi
