#!/bin/bash

query=$*
[ -z $query ] && exit 1
list=$(torrentscrap "$(echo $query | sed 's/ /+/g')")
choice=$(echo "$list" | fzf)
download=$(echo $choice | awk '{print $NF}')
! [ -z $download ] && aria2c https://nyaa.si$download &
