#!/bin/sh 

file=~/.config/zathura/zathurarc

cat > $file << EOF
set recolor-darkcolor "$(colorsXresources zathura.background)"
set recolor-lightcolor "$(colorsXresources zathura.foreground)"
set inputbar-fg "$(colorsXresources zathura.background)"
set inputbar-bg "$(colorsXresources zathura.foreground)"
set statusbar-fg "$(colorsXresources zathura.background)"
set statusbar-bg "$(colorsXresources zathura.foreground)"
map i recolor
set selection-clipboard clipboard
EOF
